// Date: 2/20/2016 12:03:42 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package com.blaxout1213.entity;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelPhoenix extends ModelBase
{
  //fields
    ModelRenderer LegRight;
    ModelRenderer LegLeft;
    ModelRenderer TalonRight;
    ModelRenderer TalonLeft;
    ModelRenderer Body;
    ModelRenderer Tail;
    ModelRenderer WingRight;
    ModelRenderer WingLeft;
    ModelRenderer Head;
  
  public ModelPhoenix()
  {
    textureWidth = 64;
    textureHeight = 64;
    
      LegRight = new ModelRenderer(this, 57, 0);
      LegRight.addBox(0F, 0F, 0F, 1, 3, 1);
      LegRight.setRotationPoint(0F, 21F, 0F);
      LegRight.setTextureSize(64, 64);
      LegRight.mirror = true;
      setRotation(LegRight, 0F, 0F, 0F);
      LegLeft = new ModelRenderer(this, 52, 0);
      LegLeft.addBox(0F, 0F, 0F, 1, 3, 1);
      LegLeft.setRotationPoint(-2F, 21F, 0F);
      LegLeft.setTextureSize(64, 64);
      LegLeft.mirror = true;
      setRotation(LegLeft, 0F, 0F, 0F);
      TalonRight = new ModelRenderer(this, 57, 5);
      TalonRight.addBox(0F, 0F, 0F, 1, 0, 1);
      TalonRight.setRotationPoint(0F, 24F, -1F);
      TalonRight.setTextureSize(64, 64);
      TalonRight.mirror = true;
      setRotation(TalonRight, 0F, 0F, 0F);
      TalonLeft = new ModelRenderer(this, 52, 5);
      TalonLeft.addBox(0F, 0F, 0F, 1, 0, 1);
      TalonLeft.setRotationPoint(-2F, 24F, -1F);
      TalonLeft.setTextureSize(64, 64);
      TalonLeft.mirror = true;
      setRotation(TalonLeft, 0F, 0F, 0F);
      Body = new ModelRenderer(this, 0, 24);
      Body.addBox(-2F, -1F, -3F, 3, 2, 6);
      Body.setRotationPoint(0F, 20F, -2F);
      Body.setTextureSize(64, 64);
      Body.mirror = true;
      setRotation(Body, 0F, 0F, 0F);
      Tail = new ModelRenderer(this, 0, 17);
      Tail.addBox(-1F, 0F, 0F, 2, 0, 7);
      Tail.setRotationPoint(-0.5F, 19F, 1F);
      Tail.setTextureSize(64, 64);
      Tail.mirror = true;
      setRotation(Tail, -0.2602503F, 0F, 0F);
      WingRight = new ModelRenderer(this, 0, 33);
      WingRight.addBox(0F, 0F, -2F, 8, 0, 4);
      WingRight.setRotationPoint(1F, 19F, -2F);
      WingRight.setTextureSize(64, 64);
      WingRight.mirror = true;
      setRotation(WingRight, 0F, 0F, 0F);
      WingLeft = new ModelRenderer(this, 0, 38);
      WingLeft.addBox(-8F, 0F, -2F, 8, 0, 4);
      WingLeft.setRotationPoint(-2F, 19F, -2F);
      WingLeft.setTextureSize(64, 64);
      WingLeft.mirror = true;
      setRotation(WingLeft, 0F, 0F, 0F);
      Head = new ModelRenderer(this, 41, 0);
      Head.addBox(-1.5F, 0F, -2F, 3, 1, 2);
      Head.setRotationPoint(-0.5333334F, 19F, -5F);
      Head.setTextureSize(64, 64);
      Head.mirror = true;
      setRotation(Head, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    LegRight.render(f5);
    LegLeft.render(f5);
    TalonRight.render(f5);
    TalonLeft.render(f5);
    Body.render(f5);
    Tail.render(f5);
    Tail.rotateAngleX = -(float)Math.cos(f2)/8;
    WingRight.render(f5);
    WingRight.rotateAngleZ = (float)Math.cos(f2);
    WingLeft.render(f5);
    WingLeft.rotateAngleZ = -(float)Math.cos(f2);
    Head.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
